services:
  db:
    image: postgres:16-alpine
    container_name: transactmanager-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  
  api:
    build:
      context: .
    container_name: transactmanager-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database={POSTGRES_DB};Username={POSTGRES_USER};Password={POSTGRES_PASSWORD}
      - Jwt__Key={JWT_KEY}

volumes:
  pgdata: